<a href="https://colab.research.google.com/github/Ansariboys88/Ansariboys88.github.io/blob/master/Matrix_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Name:- MOHD NAZIM ANSARI**

**Reg No:- 19BAI10088**

In [2]:
import numpy as np
import pandas as pd
import csv

In [19]:
#Reading datasets
df1 = pd.read_csv("check1.csv",header = None, prefix="var")
df2 = pd.read_csv("check2.csv", header = None, prefix="var")
df3 = pd.read_csv("check3.csv", header = None, prefix="var")

    
#converting data to 2D array
M1 =np.array(df1)
print(M1)

M2 = np.array(df2)
print(M2)

M3 = np.array(df3)
print(M3)


[[23  4 34]
 [32 53 12]
 [44 65 42]]
[[33 53]
 [52  1]
 [23 29]]
[[56  7 45]
 [77 43 23]
 [34 65 12]]


In [4]:
#Transpose
print(np.transpose(M1))
print(np.transpose(M2))
print(np.transpose(M3))

[[23 32 44]
 [ 4 53 65]
 [34 12 42]]
[[33 52 23]
 [53  1 29]]
[[56 77 34]
 [ 7 43 65]
 [45 23 12]]


In [17]:
#Multiplication using loops

if(len(M2[0])== len(M1)):
    
    res = [[0 for x in range(len(M2[0]))] for y in range(len(M1))]


    for i in range(len(M1)):
        for j in range(len(M2[0])):
            for k in range(len(M2)):
  
                #resulted matrix
                res[i][j] += M1[i][k] * M2[k][j]
         

In [7]:
#Multiplication using numpy
res = [[0 for x in range(len(M2[0]))] for y in range(len(M1))]
res = np.matmul(M1,M2)
print(res)

[[1749 2209]
 [4088 2097]
 [5798 3615]]


In [8]:
#Addition
print(M1+M3)

[[ 79  11  79]
 [109  96  35]
 [ 78 130  54]]


In [9]:
#Subtraction
print(M1-M3)

[[-33  -3 -11]
 [-45  10 -11]
 [ 10   0  30]]


In [10]:
#Division
print(M1/M3)

[[0.41071429 0.57142857 0.75555556]
 [0.41558442 1.23255814 0.52173913]
 [1.29411765 1.         3.5       ]]
